#!/bin/sh
#Check if ffmpeg is available
if [ ! -x $(command -v ffmpeg) ]; then
	echo "ffmpeg is not installed"
	exit 1
fi
#ensure first param is m4a
if [ ! -r "$1" ] && [ "$1" != "*.m4a" ]; then 
	echo "input a path to an m4a file"
fi
#ensure second param is cue
if [ ! -r "$2" ] && [ "$2" != "*.cue" ]; then 
	echo "input a path to an cue file"
fi
convert_to_ms() {
	prefix=$(echo $1 | head -c 5)
	frames=$(echo $1 | tail -c 3)
	frames=${frames##0}
	frames=$(($frames * 100 / 75))
	printf $prefix.$frames
}
#Iterate over cue file
while IFS= read -r line || [ -n "$line" ]; do
	trim=${line#${line%%[![:space:]]*}}
	case $trim in
		TRACK*AUDIO)
			track_num=${trim##TRACK\ }
			track_num=${track_num%%AUDIO}
			continue;;
		TITLE\ *)
			title=${trim##TITLE\ }
			continue;;
		INDEX\ 00*)
			end_time=$(convert_to_ms ${trim##INDEX\ 00\ })
			[ $index -eq 1 ] && ffmpeg -i $1 -acodec copy -ss $start_time -to $end_time "$this_track_num - $this_performer - $this_title.m4a"
			index=0
			continue;;
		INDEX\ 01*)
			end_time=$(convert_to_ms ${trim##INDEX\ 01\ })
			[ $index -eq 1 ] && ffmpeg -i $1 -acodec copy -ss $start_time -to $end_time "$this_track_num - $this_performer - $this_title.m4a"
			start_time=$end_time
			this_track_num=$track_num
			this_performer=$performer
			this_title=$title
			index=1
			continue;;
		PERFORMER\ *)
			performer=${trim##PERFORMER\ }
			continue;;
	esac
done < "$2"
end_time=$(ffprobe -i $1 -show_entries format=duration -v quiet -of csv="p=0" -sexagesimal)
ffmpeg -i $1 -acodec copy -ss $start_time -to $end_time "$this_track_num - $this_performer - $this_title.m4a"


